# -*- coding: utf-8 -*-
"""Number Guesser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GxOXs0OeIiL9RSD_mcC5XyEaHiNDGTKb
"""

import random
import math

lb = int(input("Enter lower range: "))
ub = int(input("Enter upper range: "))

x = random.randint(lb, ub)
maxguess = round(math.log(ub - lb + 1), 0)

print("You only have ", maxguess, "chances to guess this number!")

count = 0

while count < maxguess:
  count += 1
  guess = int(input("Guess a number!!!!!!: "))
  if x == guess:
    print("Congratulations?? You think you're so smart? It really took you", count, "tries to get it??")
    break
  elif x < guess:
    print("CALM DOWN BUDDY JEEZ IT'S NOT THAT BIG!!")
  elif x > guess:
    print("WHAT WHY IN THE WORLD WOULD IT BE THAT SMALL???")

if count >= maxguess:
  print("HAHAHAHH HOW IS IT THIS POSSIBLE TO BE THIS BAD AT SOMETHING? THE NUMBER WAS LITERALLY", x)